### ISSUE TITLE
Bugs with `gaussian_blur_f32` when sigma <= 0.0

### ISSUE THREAD

**Issue by Aloxaf** [image-rs/imageproc#331]
# Sigma == 0.0
`gaussian_blur_f32` will clean my image

```rust
use image::{RgbImage, Rgb};
use imageproc::filter::gaussian_blur_f32;
use imageproc::drawing::draw_filled_circle_mut;

fn main() {
    let mut image = RgbImage::new(200, 200);
    draw_filled_circle_mut(&mut image, (100, 100), 100, Rgb([255, 255, 255]));
    let _ = image.save("original.png");
    let _ = gaussian_blur_f32(&image, 0.0).save("zero.png");
}
```

original.png
![original](https://user-images.githubusercontent.com/17017672/60756609-f1146c80-a031-11e9-99ce-f5c0f60f0c9c.png)

zero.png
![zero](https://user-images.githubusercontent.com/17017672/60756612-f4a7f380-a031-11e9-9361-dfa6b8ee5073.png)

# Sigma <= - 1.0
`gaussian_blur_f32` will cause panic

## Backtrace

```
thread 'main' panicked at 'attempt to multiply with overflow', /home/aloxaf/.cargo/registry/src/github.com-1ecc6299db9ec823/imageproc-0.18.0/src/filter/mod.rs:157:37
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:382
   8: rust_begin_unwind
             at src/libstd/panicking.rs:309
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic
             at src/libcore/panicking.rs:49
  11: imageproc::filter::gaussian_kernel_f32
             at /home/aloxaf/.cargo/registry/src/github.com-1ecc6299db9ec823/imageproc-0.18.0/src/filter/mod.rs:157
  12: imageproc::filter::gaussian_blur_f32
             at /home/aloxaf/.cargo/registry/src/github.com-1ecc6299db9ec823/imageproc-0.18.0/src/filter/mod.rs:175
  13: tmp2::main
             at src/main.rs:9
  14: std::rt::lang_start::{{closure}}
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libstd/rt.rs:64
  15: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  16: std::panicking::try::do_call
             at src/libstd/panicking.rs:294
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  18: std::panicking::try
             at src/libstd/panicking.rs:273
  19: std::panic::catch_unwind
             at src/libstd/panic.rs:388
  20: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  21: std::rt::lang_start
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libstd/rt.rs:64
  22: main
  23: __libc_start_main
  24: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I think when sigma <= 0.0, `gaussian_kernel_f32` should just return a copy of the original image.

**Comment by theotherphil** [comment]
The Gaussian function isn't defined when sigma is zero, and standard deviation cannot be negative, so I think both cases the best behaviour is to panic rather than silently do something incorrect.

This is one of many places in this library where we could opt to return `Result`s but instead panic. We may decide to switch to using `Result`s at some point, but if so we should do it across all functions rather than just this one.

**Comment by Aloxaf** [comment]
@theotherphil  Thanks for you reply. I'm agree with you
