### ISSUE TITLE
Panicked while drawing huge ellipse.

### ISSUE THREAD

**Issue by eternal-io** [image-rs/imageproc#519]
## Very easy to reproduce:

``` rust
#[cfg(test)]
mod tests {
    #[test]
    fn test() {
        let mut img = image::RgbImage::new(1920, 1080);
        imageproc::drawing::draw_filled_ellipse_mut(
            &mut img,
            (960, 540),
            960,
            540,
            image::Rgb([0, 0, 0]),
        );
    }
}
```

## then ...

``` plaintext
thread 'tests::test' panicked at 'attempt to multiply with overflow', D:\.cargo\registry\src\github.com-1ecc6299db9ec823\imageproc-0.23.0\src\drawing\conics.rs:175:50
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panicking.rs:579
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\panicking.rs:64
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\panicking.rs:114
   3: imageproc::drawing::conics::draw_ellipse
             at D:\.cargo\registry\src\github.com-1ecc6299db9ec823\imageproc-0.23.0\src\drawing\conics.rs:178
   4: imageproc::drawing::conics::draw_filled_ellipse_mut<image::buffer_::ImageBuffer<image::color::Rgb<u8>,alloc::vec::Vec<u8,alloc::alloc::Global> > >
             at D:\.cargo\registry\src\github.com-1ecc6299db9ec823\imageproc-0.23.0\src\drawing\conics.rs:139
   5: quadim::tests::test
             at .\src\main.rs:483
   6: quadim::tests::test::closure$0
             at .\src\main.rs:481
   7: core::ops::function::FnOnce::call_once<quadim::tests::test::closure_env$0,tuple$<> >
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\core\src\ops\function.rs:250       
   8: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\ops\function.rs:250 
```

Seems `i32` are too small for some use cases. But once `overflow-checks = false` was setted in Cargo profile, run my program completely, a cropped ellipse has been drawed, as you can see in the upper left corner of the picture:

![2](https://user-images.githubusercontent.com/36335359/235201244-717b971d-1df2-4e0f-992c-e9704c2dd58f.png)

*(Yes, an image-quadtree program ;)*

**Comment by cospectrum** [comment]
We should consider upgrading to `i64` if that solves the problem.
